<?php

namespace Waf;

const ERR_AUTOLOAD_FAILED = \YAF\ERR\AUTOLOAD_FAILED;
const ERR_NOTFOUND_MODULE = \YAF\ERR\NOTFOUND\MODULE;
const ERR_NOTFOUND_CONTROLLER = \YAF\ERR\NOTFOUND\CONTROLLER;
const ERR_NOTFOUND_ACTION = \YAF\ERR\NOTFOUND\ACTION;
const ERR_NOTFOUND_VIEW = \YAF\ERR\NOTFOUND\VIEW;

